export const ADD_POST = 'ADD_POST';
export type ADD_POST = typeof ADD_POST;

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export type ADD_NOTIFICATION = typeof ADD_NOTIFICATION;

export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export type REMOVE_NOTIFICATION = typeof REMOVE_NOTIFICATION;

export const SHOW_NOTIFICATIONS = 'SHOW_NOTIFICATIONS';
export type SHOW_NOTIFICATIONS = typeof SHOW_NOTIFICATIONS;

export const HIDE_NOTIFICATIONS = 'HIDE_NOTIFICATIONS';
export type HIDE_NOTIFICATIONS = typeof HIDE_NOTIFICATIONS;

export const REQUEST_POSTS = 'REQUEST_POSTS';
export type REQUEST_POSTS = typeof REQUEST_POSTS;

export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export type RECEIVE_POSTS = typeof RECEIVE_POSTS;

export const UPDATE_POST = 'UPDATE_POST';
export type UPDATE_POST = typeof UPDATE_POST;

export const UPDATE_UI = 'UPDATE_UI';
export type UPDATE_UI = typeof UPDATE_UI;
